/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    configuration: Configuration;
    media: Media;
    videos: Video;
    products: Product;
    productCategories: ProductCategory;
    users: User;
    tenants: Tenant;
    forms: Form;
    'form-submissions': FormSubmission;
    exports: Export;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    productCategories: {
      products: 'products';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    configuration: ConfigurationSelect<false> | ConfigurationSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    productCategories: ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('es' | 'en' | 'de' | 'es-ar')
    | ('es' | 'en' | 'de' | 'es-ar')[];
  globals: {};
  globalsSelect: {};
  locale: 'es' | 'en' | 'de' | 'es-ar';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  tenant?: (string | null) | Tenant;
  title?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  layout: (
    | {
        title?: string | null;
        subtitle?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        background?: (string | null) | Media;
        /**
         * Optional. Wenn ein Video hinzugefügt wird, ersetzt es das Hintergrundbild.
         */
        video?: (string | null) | Video;
        logo?: (string | null) | Media;
        logoSize?: ('small' | 'medium' | 'large' | 'xlarge') | null;
        logoPosition?: ('left' | 'center' | 'right') | null;
        links?:
          | {
              link?: {
                label?: string | null;
                newTab?: boolean | null;
                type?: ('reference' | 'custom') | null;
                reference?: {
                  relationTo: 'pages';
                  value: string | Page;
                } | null;
                url?: string | null;
                /**
                 * Choose how the link should be rendered.
                 */
                appearance?: ('primary' | 'secondary') | null;
              };
              id?: string | null;
            }[]
          | null;
        contentPlacement?: ('top-left' | 'center' | 'bottom-left') | null;
        height?: ('fullscreen' | 'large' | 'medium' | 'small') | null;
        overlay?: ('dark' | 'none') | null;
        /**
         * Helle Schrift für dunkle Hintergründe, dunkle Schrift für helle Hintergründe.
         */
        textColor?: ('light' | 'dark') | null;
        is_animated?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        images: {
          image: string | Media;
          id?: string | null;
        }[];
        layout: 'gallery' | 'separator' | 'slider';
        slidesPerView?: number | null;
        showAsCard?: boolean | null;
        /**
         * Abstand zwischen den Slides in Pixeln
         */
        slideGap?: number | null;
        /**
         * Höhe in REM
         */
        cardHeight?: number | null;
        motionType: 'smooth' | 'bumpy';
        bumpySpeed?: number | null;
        smoothSpeed?: number | null;
        section?: {
          title?: string | null;
          subtitle?: string | null;
          align?: ('left' | 'center' | 'right') | null;
          withLine?: boolean | null;
          backgroundColor?: string | null;
          backgroundImage?: (string | null) | Media;
          fullWidth?: boolean | null;
          padding?: {
            top?: number | null;
            bottom?: number | null;
            left?: number | null;
            right?: number | null;
          };
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'gallery';
      }
    | {
        form_title: string;
        form: string | Form;
        id?: string | null;
        blockName?: string | null;
        blockType: 'form';
      }
    | {
        section?: {
          title?: string | null;
          subtitle?: string | null;
          align?: ('left' | 'center' | 'right') | null;
          withLine?: boolean | null;
          backgroundColor?: string | null;
          backgroundImage?: (string | null) | Media;
          fullWidth?: boolean | null;
          padding?: {
            top?: number | null;
            bottom?: number | null;
            left?: number | null;
            right?: number | null;
          };
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'contact';
      }
    | {
        images?:
          | {
              image: string | Media;
              id?: string | null;
            }[]
          | null;
        text?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        imagePosition?: ('left' | 'right') | null;
        section?: {
          title?: string | null;
          subtitle?: string | null;
          align?: ('left' | 'center' | 'right') | null;
          withLine?: boolean | null;
          backgroundColor?: string | null;
          backgroundImage?: (string | null) | Media;
          fullWidth?: boolean | null;
          padding?: {
            top?: number | null;
            bottom?: number | null;
            left?: number | null;
            right?: number | null;
          };
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'text';
      }
    | {
        menu?: {
          allergens?: ('1' | '2') | null;
        };
        section?: {
          title?: string | null;
          subtitle?: string | null;
          align?: ('left' | 'center' | 'right') | null;
          withLine?: boolean | null;
          backgroundColor?: string | null;
          backgroundImage?: (string | null) | Media;
          fullWidth?: boolean | null;
          padding?: {
            top?: number | null;
            bottom?: number | null;
            left?: number | null;
            right?: number | null;
          };
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'products';
      }
    | {
        picker?: {
          size?: ('small' | 'medium' | 'large') | null;
          rounded?: boolean | null;
        };
        section?: {
          title?: string | null;
          subtitle?: string | null;
          align?: ('left' | 'center' | 'right') | null;
          withLine?: boolean | null;
          backgroundColor?: string | null;
          backgroundImage?: (string | null) | Media;
          fullWidth?: boolean | null;
          padding?: {
            top?: number | null;
            bottom?: number | null;
            left?: number | null;
            right?: number | null;
          };
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'language-picker';
      }
    | {
        embed?: {
          url?: string | null;
        };
        section?: {
          title?: string | null;
          subtitle?: string | null;
          align?: ('left' | 'center' | 'right') | null;
          withLine?: boolean | null;
          backgroundColor?: string | null;
          backgroundImage?: (string | null) | Media;
          fullWidth?: boolean | null;
          padding?: {
            top?: number | null;
            bottom?: number | null;
            left?: number | null;
            right?: number | null;
          };
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'embed';
      }
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: string;
  name: string;
  /**
   * Used for domain-based tenant handling
   */
  domain?: string | null;
  /**
   * Used for url paths, example: /tenant-slug/page-slug
   */
  slug: string;
  /**
   * If checked, logging in is not required to read. Useful for building public pages.
   */
  allowPublicRead?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  tenant?: (string | null) | Tenant;
  /**
   * Search engines use alt text to understand the content of an image, as they cannot "see" images themselves.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    seo?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: string;
  tenant?: (string | null) | Tenant;
  compressionStatus?: ('pending' | 'processing' | 'completed' | 'failed') | null;
  size?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuration".
 */
export interface Configuration {
  id: string;
  tenant?: (string | null) | Tenant;
  contact?: {
    schedule?:
      | {
          day?: string | null;
          time?: string | null;
          id?: string | null;
        }[]
      | null;
    phone?:
      | {
          type?: ('phone' | 'whatsapp' | 'email') | null;
          link?: string | null;
          label?: string | null;
          id?: string | null;
        }[]
      | null;
    address?: string | null;
    maps?: string | null;
  };
  social?: {
    facebook?: string | null;
    instagram?: string | null;
    youtube?: string | null;
    tiktok?: string | null;
    restaurantguru?: string | null;
    yelp?: string | null;
    tripadvisor?: string | null;
  };
  navigation?: {
    logo?: (string | null) | Media;
    sticky?: boolean | null;
    transparent?: boolean | null;
    heroMode?: boolean | null;
    borderBottom?: boolean | null;
    links?:
      | {
          link?: {
            label?: string | null;
            newTab?: boolean | null;
            type?: ('reference' | 'custom') | null;
            reference?: {
              relationTo: 'pages';
              value: string | Page;
            } | null;
            url?: string | null;
          };
          id?: string | null;
        }[]
      | null;
    actions?:
      | {
          link?: {
            label?: string | null;
            newTab?: boolean | null;
            type?: ('reference' | 'custom') | null;
            reference?: {
              relationTo: 'pages';
              value: string | Page;
            } | null;
            url?: string | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  footer?: {
    minimal?: boolean | null;
  };
  theme?: {
    background?: string | null;
    fontColor?: string | null;
    surface?: string | null;
    onSurface?: string | null;
    primary?: string | null;
    onPrimary?: string | null;
    secondary?: string | null;
    onSecondary?: string | null;
    error?: string | null;
    onError?: string | null;
    border?: string | null;
  };
  i18n?: {
    es?: boolean | null;
    en?: boolean | null;
    de?: boolean | null;
    'es-ar'?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  tenant?: (string | null) | Tenant;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  price: number;
  category: string | ProductCategory;
  allergens?:
    | (
        | 'celery'
        | 'crustaceans'
        | 'dairy'
        | 'egg'
        | 'fish'
        | 'gluten'
        | 'legumes'
        | 'mollusks'
        | 'mustard'
        | 'nuts'
        | 'peanut'
        | 'sesame'
        | 'soy'
        | 'sulfites'
      )[]
    | null;
  note?: string[] | null;
  image?: (string | null) | Media;
  available?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productCategories".
 */
export interface ProductCategory {
  id: string;
  tenant?: (string | null) | Tenant;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sortOrder?: number | null;
  image?: (string | null) | Media;
  products?: {
    docs?: (string | Product)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  additionalContent?:
    | (
        | {
            title?: string | null;
            subtitle?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            background?: (string | null) | Media;
            /**
             * Optional. Wenn ein Video hinzugefügt wird, ersetzt es das Hintergrundbild.
             */
            video?: (string | null) | Video;
            logo?: (string | null) | Media;
            logoSize?: ('small' | 'medium' | 'large' | 'xlarge') | null;
            logoPosition?: ('left' | 'center' | 'right') | null;
            links?:
              | {
                  link?: {
                    label?: string | null;
                    newTab?: boolean | null;
                    type?: ('reference' | 'custom') | null;
                    reference?: {
                      relationTo: 'pages';
                      value: string | Page;
                    } | null;
                    url?: string | null;
                    /**
                     * Choose how the link should be rendered.
                     */
                    appearance?: ('primary' | 'secondary') | null;
                  };
                  id?: string | null;
                }[]
              | null;
            contentPlacement?: ('top-left' | 'center' | 'bottom-left') | null;
            height?: ('fullscreen' | 'large' | 'medium' | 'small') | null;
            overlay?: ('dark' | 'none') | null;
            /**
             * Helle Schrift für dunkle Hintergründe, dunkle Schrift für helle Hintergründe.
             */
            textColor?: ('light' | 'dark') | null;
            is_animated?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            images: {
              image: string | Media;
              id?: string | null;
            }[];
            layout: 'gallery' | 'separator' | 'slider';
            slidesPerView?: number | null;
            showAsCard?: boolean | null;
            /**
             * Abstand zwischen den Slides in Pixeln
             */
            slideGap?: number | null;
            /**
             * Höhe in REM
             */
            cardHeight?: number | null;
            motionType: 'smooth' | 'bumpy';
            bumpySpeed?: number | null;
            smoothSpeed?: number | null;
            section?: {
              title?: string | null;
              subtitle?: string | null;
              align?: ('left' | 'center' | 'right') | null;
              withLine?: boolean | null;
              backgroundColor?: string | null;
              backgroundImage?: (string | null) | Media;
              fullWidth?: boolean | null;
              padding?: {
                top?: number | null;
                bottom?: number | null;
                left?: number | null;
                right?: number | null;
              };
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            form_title: string;
            form: string | Form;
            id?: string | null;
            blockName?: string | null;
            blockType: 'form';
          }
        | {
            section?: {
              title?: string | null;
              subtitle?: string | null;
              align?: ('left' | 'center' | 'right') | null;
              withLine?: boolean | null;
              backgroundColor?: string | null;
              backgroundImage?: (string | null) | Media;
              fullWidth?: boolean | null;
              padding?: {
                top?: number | null;
                bottom?: number | null;
                left?: number | null;
                right?: number | null;
              };
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact';
          }
        | {
            images?:
              | {
                  image: string | Media;
                  id?: string | null;
                }[]
              | null;
            text?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            imagePosition?: ('left' | 'right') | null;
            section?: {
              title?: string | null;
              subtitle?: string | null;
              align?: ('left' | 'center' | 'right') | null;
              withLine?: boolean | null;
              backgroundColor?: string | null;
              backgroundImage?: (string | null) | Media;
              fullWidth?: boolean | null;
              padding?: {
                top?: number | null;
                bottom?: number | null;
                left?: number | null;
                right?: number | null;
              };
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            menu?: {
              allergens?: ('1' | '2') | null;
            };
            section?: {
              title?: string | null;
              subtitle?: string | null;
              align?: ('left' | 'center' | 'right') | null;
              withLine?: boolean | null;
              backgroundColor?: string | null;
              backgroundImage?: (string | null) | Media;
              fullWidth?: boolean | null;
              padding?: {
                top?: number | null;
                bottom?: number | null;
                left?: number | null;
                right?: number | null;
              };
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'products';
          }
        | {
            picker?: {
              size?: ('small' | 'medium' | 'large') | null;
              rounded?: boolean | null;
            };
            section?: {
              title?: string | null;
              subtitle?: string | null;
              align?: ('left' | 'center' | 'right') | null;
              withLine?: boolean | null;
              backgroundColor?: string | null;
              backgroundImage?: (string | null) | Media;
              fullWidth?: boolean | null;
              padding?: {
                top?: number | null;
                bottom?: number | null;
                left?: number | null;
                right?: number | null;
              };
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'language-picker';
          }
        | {
            embed?: {
              url?: string | null;
            };
            section?: {
              title?: string | null;
              subtitle?: string | null;
              align?: ('left' | 'center' | 'right') | null;
              withLine?: boolean | null;
              backgroundColor?: string | null;
              backgroundImage?: (string | null) | Media;
              fullWidth?: boolean | null;
              padding?: {
                top?: number | null;
                bottom?: number | null;
                left?: number | null;
                right?: number | null;
              };
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'embed';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  roles?: ('super-admin' | 'user')[] | null;
  username?: string | null;
  tenants?:
    | {
        tenant: string | Tenant;
        roles: ('tenant-admin' | 'tenant-viewer')[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: string;
  name?: string | null;
  format?: ('csv' | 'json') | null;
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  locale?: ('all' | 'es' | 'en' | 'de' | 'es-ar') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'createCollectionExport' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'createCollectionExport' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'configuration';
        value: string | Configuration;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'videos';
        value: string | Video;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'productCategories';
        value: string | ProductCategory;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: string | Tenant;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'exports';
        value: string | Export;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  slugLock?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              subtitle?: T;
              background?: T;
              video?: T;
              logo?: T;
              logoSize?: T;
              logoPosition?: T;
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          label?: T;
                          newTab?: T;
                          type?: T;
                          reference?: T;
                          url?: T;
                          appearance?: T;
                        };
                    id?: T;
                  };
              contentPlacement?: T;
              height?: T;
              overlay?: T;
              textColor?: T;
              is_animated?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              layout?: T;
              slidesPerView?: T;
              showAsCard?: T;
              slideGap?: T;
              cardHeight?: T;
              motionType?: T;
              bumpySpeed?: T;
              smoothSpeed?: T;
              section?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    align?: T;
                    withLine?: T;
                    backgroundColor?: T;
                    backgroundImage?: T;
                    fullWidth?: T;
                    padding?:
                      | T
                      | {
                          top?: T;
                          bottom?: T;
                          left?: T;
                          right?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        form?:
          | T
          | {
              form_title?: T;
              form?: T;
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              section?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    align?: T;
                    withLine?: T;
                    backgroundColor?: T;
                    backgroundImage?: T;
                    fullWidth?: T;
                    padding?:
                      | T
                      | {
                          top?: T;
                          bottom?: T;
                          left?: T;
                          right?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              text?: T;
              imagePosition?: T;
              section?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    align?: T;
                    withLine?: T;
                    backgroundColor?: T;
                    backgroundImage?: T;
                    fullWidth?: T;
                    padding?:
                      | T
                      | {
                          top?: T;
                          bottom?: T;
                          left?: T;
                          right?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        products?:
          | T
          | {
              menu?:
                | T
                | {
                    allergens?: T;
                  };
              section?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    align?: T;
                    withLine?: T;
                    backgroundColor?: T;
                    backgroundImage?: T;
                    fullWidth?: T;
                    padding?:
                      | T
                      | {
                          top?: T;
                          bottom?: T;
                          left?: T;
                          right?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        'language-picker'?:
          | T
          | {
              picker?:
                | T
                | {
                    size?: T;
                    rounded?: T;
                  };
              section?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    align?: T;
                    withLine?: T;
                    backgroundColor?: T;
                    backgroundImage?: T;
                    fullWidth?: T;
                    padding?:
                      | T
                      | {
                          top?: T;
                          bottom?: T;
                          left?: T;
                          right?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        embed?:
          | T
          | {
              embed?:
                | T
                | {
                    url?: T;
                  };
              section?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    align?: T;
                    withLine?: T;
                    backgroundColor?: T;
                    backgroundImage?: T;
                    fullWidth?: T;
                    padding?:
                      | T
                      | {
                          top?: T;
                          bottom?: T;
                          left?: T;
                          right?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuration_select".
 */
export interface ConfigurationSelect<T extends boolean = true> {
  tenant?: T;
  contact?:
    | T
    | {
        schedule?:
          | T
          | {
              day?: T;
              time?: T;
              id?: T;
            };
        phone?:
          | T
          | {
              type?: T;
              link?: T;
              label?: T;
              id?: T;
            };
        address?: T;
        maps?: T;
      };
  social?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        youtube?: T;
        tiktok?: T;
        restaurantguru?: T;
        yelp?: T;
        tripadvisor?: T;
      };
  navigation?:
    | T
    | {
        logo?: T;
        sticky?: T;
        transparent?: T;
        heroMode?: T;
        borderBottom?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    label?: T;
                    newTab?: T;
                    type?: T;
                    reference?: T;
                    url?: T;
                  };
              id?: T;
            };
        actions?:
          | T
          | {
              link?:
                | T
                | {
                    label?: T;
                    newTab?: T;
                    type?: T;
                    reference?: T;
                    url?: T;
                  };
              id?: T;
            };
      };
  footer?:
    | T
    | {
        minimal?: T;
      };
  theme?:
    | T
    | {
        background?: T;
        fontColor?: T;
        surface?: T;
        onSurface?: T;
        primary?: T;
        onPrimary?: T;
        secondary?: T;
        onSecondary?: T;
        error?: T;
        onError?: T;
        border?: T;
      };
  i18n?:
    | T
    | {
        es?: T;
        en?: T;
        de?: T;
        'es-ar'?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        seo?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  tenant?: T;
  compressionStatus?: T;
  size?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  description?: T;
  price?: T;
  category?: T;
  allergens?: T;
  note?: T;
  image?: T;
  available?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productCategories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  description?: T;
  sortOrder?: T;
  image?: T;
  products?: T;
  additionalContent?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              subtitle?: T;
              background?: T;
              video?: T;
              logo?: T;
              logoSize?: T;
              logoPosition?: T;
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          label?: T;
                          newTab?: T;
                          type?: T;
                          reference?: T;
                          url?: T;
                          appearance?: T;
                        };
                    id?: T;
                  };
              contentPlacement?: T;
              height?: T;
              overlay?: T;
              textColor?: T;
              is_animated?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              layout?: T;
              slidesPerView?: T;
              showAsCard?: T;
              slideGap?: T;
              cardHeight?: T;
              motionType?: T;
              bumpySpeed?: T;
              smoothSpeed?: T;
              section?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    align?: T;
                    withLine?: T;
                    backgroundColor?: T;
                    backgroundImage?: T;
                    fullWidth?: T;
                    padding?:
                      | T
                      | {
                          top?: T;
                          bottom?: T;
                          left?: T;
                          right?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        form?:
          | T
          | {
              form_title?: T;
              form?: T;
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              section?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    align?: T;
                    withLine?: T;
                    backgroundColor?: T;
                    backgroundImage?: T;
                    fullWidth?: T;
                    padding?:
                      | T
                      | {
                          top?: T;
                          bottom?: T;
                          left?: T;
                          right?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              text?: T;
              imagePosition?: T;
              section?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    align?: T;
                    withLine?: T;
                    backgroundColor?: T;
                    backgroundImage?: T;
                    fullWidth?: T;
                    padding?:
                      | T
                      | {
                          top?: T;
                          bottom?: T;
                          left?: T;
                          right?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        products?:
          | T
          | {
              menu?:
                | T
                | {
                    allergens?: T;
                  };
              section?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    align?: T;
                    withLine?: T;
                    backgroundColor?: T;
                    backgroundImage?: T;
                    fullWidth?: T;
                    padding?:
                      | T
                      | {
                          top?: T;
                          bottom?: T;
                          left?: T;
                          right?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        'language-picker'?:
          | T
          | {
              picker?:
                | T
                | {
                    size?: T;
                    rounded?: T;
                  };
              section?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    align?: T;
                    withLine?: T;
                    backgroundColor?: T;
                    backgroundImage?: T;
                    fullWidth?: T;
                    padding?:
                      | T
                      | {
                          top?: T;
                          bottom?: T;
                          left?: T;
                          right?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        embed?:
          | T
          | {
              embed?:
                | T
                | {
                    url?: T;
                  };
              section?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    align?: T;
                    withLine?: T;
                    backgroundColor?: T;
                    backgroundImage?: T;
                    fullWidth?: T;
                    padding?:
                      | T
                      | {
                          top?: T;
                          bottom?: T;
                          left?: T;
                          right?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  username?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        roles?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  domain?: T;
  slug?: T;
  allowPublicRead?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  locale?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    name?: string | null;
    format?: ('csv' | 'json') | null;
    limit?: number | null;
    page?: number | null;
    sort?: string | null;
    sortOrder?: ('asc' | 'desc') | null;
    locale?: ('all' | 'es' | 'en' | 'de' | 'es-ar') | null;
    drafts?: ('yes' | 'no') | null;
    selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
    fields?: string[] | null;
    collectionSlug: string;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    user?: string | null;
    userCollection?: string | null;
    exportsCollection?: string | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'products';
          value: string | Product;
        } | null)
      | ({
          relationTo: 'productCategories';
          value: string | ProductCategory;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}